services:
  postgres:
    container_name: postgres-airbnb
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      PGDATA: /var/lib/postgressql/data
      POSTGRES_DB: AirBnB_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
#  mail-dev:
#    container_name: mail-dev-book
#    image: maildev/maildev
#    ports:
#      - 1080:1080
#      - 1025:1025

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
