

logging:
  level:
    ROOT: info
    org.hibernate.sql: DEBUG
    com.example.AirbnbBackEnd: DEBUG
spring:
  profiles:
    active: dev
  application:
    name: AirbnbBackEnd
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: Hikari
      auto-commit: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: airbnb
  liquibase:
    contexts: dev
    enabled: true
    change-log: classpath:db/changelog/master.xml
    default-schema: airbnb

  servlet:
    multipart:
      max-file-size: 100MB
      enabled: true
      max-request-size: 100MB

server:
  port: 8080

okta:
  oauth2:
    issuer: https://dev-3z2md4l4phe4p3l7.us.auth0.com/
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_CLIENT_SECRET}

application:
  auth0:
    role-landlord-id: rol_ZDd29YVp2yAovATS

debug: true
